version: "3"
networks:
    ezbids:

services:
    mongodb:
        container_name: brainlife_ezbids-mongodb
        image: mongo:4.4.15
        platform: linux/amd64
        volumes:
            - /data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
        ports:
            - 27417:27017
        networks:
            - ezbids

    api:
        container_name: brainlife_ezbids-api
        build: .
        image: ezbids-api   # <-- explicitly set this
        platform: linux/amd64
        volumes:
            - ./api:/app/api
            - /tmp:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
        working_dir: /app/api
        command:
            ./dev.sh
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
            BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION}
        ports:
            - 8082:8082
        networks:
            - ezbids

    handler:
        container_name: brainlife_ezbids-handler
        build: ./handler
        image: ezbids-handler  # <-- explicitly set this
        platform: linux/amd64
        volumes:
            - .:/app
            - /tmp:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
            api:
                condition: service_healthy
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
        networks:
            - ezbids
        tty: true
        command: pm2 start handler.js --attach --watch --ignore-watch "ui **/node_modules"

    ui:
        container_name: brainlife_ezbids-ui
        env_file:
            - .env
        build: ./ui
        image: ezbids-ui   # <-- explicitly set this
        platform: linux/amd64
        volumes:
            - ./ui/src:/ui/src
        environment:
            VITE_APIHOST: http://localhost:8082
            VITE_BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000"]
        ports:
            - 3000:3000
        networks:
            - ezbids

    telemetry:
        container_name: brainlife_ezbids-telemetry
        build: ./telemetry
        image: ezbids-telemetry   # <-- explicitly set this
        platform: linux/amd64
        depends_on:
            - mongodb
        profiles: ["telemetry"]
        ports:
            - 8000:8000
        networks:
            - ezbids

