networks:
    ezbids:

services:
    mongodb:
        container_name: brainlife_ezbids-mongodb
        image: mongo:4.4.15
        platform: linux/amd64
        volumes:
            - /data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries:
                5
        networks:
            - ezbids

    api:
        container_name: brainlife_ezbids-api
        build: .
        platform: linux/amd64
        volumes:
            - ${EZBIDS_TMP_DIR:-/tmp/ezbids-workdir}:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
        working_dir: /app/api
        command:
            ./dev.sh
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
            BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION:-false}
        networks:
            - ezbids

    handler:
        container_name: brainlife_ezbids-handler
        build:
            context: .
            dockerfile: handler/Dockerfile
        platform: linux/amd64
        volumes:
            - ${EZBIDS_TMP_DIR:-/tmp/ezbids-workdir}:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
            api:
                condition: service_healthy
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
            PRESORT: ${PRESORT:-false}
        networks:
            - ezbids
        tty: true #turn on color for bids-validator output
        command: pm2 start handler.js --attach

    ui:
        # we only run this container to build the UI pages to mount into a volume
        # for use in the nginx container.
        container_name: brainlife_ezbids-ui-builder
        build: 
            context: ./ui/
            dockerfile: Dockerfile-production
        platform: linux/amd64
        environment:
            VITE_APIHOST: https://${SERVER_NAME}/api
            VITE_BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION:-false}
            BRAINLIFE_USE_NGINX: true
        volumes:
            - ui_dist:/ui/dist
        command: tail -f /dev/null # Keep container running

    # by default this is not enabled, add COMPOSE_PROFILES=telemetry to your .env
    telemetry:
        container_name: brainlife_ezbids-telemetry
        build: ./telemetry
        platform: linux/amd64
        depends_on:
            - mongodb
        profiles: ["telemetry"]
        networks:
            - ezbids

    nginx:
        container_name: brainlife_ezbids-nginx
        depends_on:
            - ui
            - api
        image: nginx:latest
        platform: linux/amd64
        ports:
            - 443:443
        networks:
            - ezbids
        volumes:
            # we do mount ssl certs and the built portions of the ui pages
            # in this docker compose versus the locally hosted one. The ssl mounts
            # are a necessity, while the ui_dist mount enables us to eliminate 1
            # container since we're serving the page with nginx.
            - ./nginx/ssl/:/etc/nginx/conf.d/ssl/
            - ./nginx/production_nginx.conf:/etc/nginx/conf.d/default.conf
            - ui_dist:/usr/share/nginx/html/ezbids:ro

volumes:
    ui_dist:
